Feature/canvasLayer/22　レイヤー実装途中経過
TeamDotArt/dotart_frontend pull request #25
Opened 2021-10-20 03:52 UTC by zinNORI

レイヤー実装途中経過
再描画部分とdrawdotの改修中

2021-10-20 17:09 UTC, RimlTempest commented
![pekora](https://user-images.githubusercontent.com/38300385/138139401-a7f022ac-e216-434e-a80c-337e789ed111.jpg)
進捗確認しました

2021-10-25 02:39 UTC, Tukudanium commented
現在確認できているバグ
・アンドゥリドゥ周り
・一番上のレイヤー以外に書くとき見た目に反映されない（更新したら反映される）
・素早く書いたときに見た目で飛び飛びになる（更新したら治る）

2021-10-25 02:41 UTC, Tukudanium commented
おそらく問題なく機能しているもの
・reDraw
・レイヤー追加、削除、変更、順番変更

2021-10-26 03:43 UTC, Tukudanium commented
修正済みの項目
・一番上のレイヤー以外に書くとき見た目に反映されないこと
・複数レイヤーに書いた時の適切な処理
・画像の回転　レイヤーごとの処理を実装済み

よくわからないもの
・素早く書いたときに見た目で飛び飛びになる
いつの間にか治っていたが原因不明　もうしばらく様子見

確認できたがまだ直っていないもの
・アンドゥリドゥ
一番最初から作成してあるレイヤーだと問題なく動くが、後から追加したレイヤーで最後の一個が巻き戻せない

現在のレイヤーの指定などで仕様が少し把握しきれていないところがあるのでもうすこし固める

2021-10-26 04:29 UTC, RimlTempest commented
![DD8916CC-31D6-49C0-888D-E13543C6853C](https://user-images.githubusercontent.com/38300385/138808968-82159982-5b4a-4d40-9124-e42e5f0de62e.gif)

進捗確認しましt

2021-10-27 04:25 UTC, Tukudanium commented
こちらはですね、私が作った。これ作ったんかな？や作ってないかもしれへんわ。紹介すんのやめとくわ。確信がないわ。作ってるかどうかわからへんから。ここに、えーなんやったっけ、まなんか進捗ありますね。ここにざっと、こういう感じです。で。奥に見えるのがレイヤー機能でございます。

2021-10-27 04:27 UTC, Tukudanium commented
素早く書いたときに見た目で飛び飛びになる件はdrawDotの問題で修正済みなので多分大丈夫でｽｳｩｩｩｩ

2021-10-27 04:40 UTC, RimlTempest commented on composables/useAfterDraw.ts
> +// import { Stack } from '@/types/Canvas/StackType';
使用しないのでコメント削除する

2021-10-27 04:48 UTC, RimlTempest commented on composables/useLayerReDraw.ts
> +                return 1;
enumか定数に数値を置き換えて値がなんなのかわかりやすいようにする

2021-10-27 04:51 UTC, RimlTempest commented on composables/useLayerReDraw.ts
> +                    .map(function (item) {
上記のfilterの記述と合わせて下のmapも同じような記述に揃えたほうがいい

```
.map((item) => {
    return item.layerIndex;
})
```

2021-10-27 04:53 UTC, RimlTempest commented on composables/useLayerReDraw.ts
> +                        layer.layerIndex === Math.min.apply(null, layernums)
第一引数はnullよりundifinedのほうが良さそう

2021-10-27 04:54 UTC, RimlTempest commented on composables/useLayerReDraw.ts
> +) {
返却値の型定義をする
現状numberで返してるので

```ts
function checkCanvas(~): number {
~
}
```

のようにする

2021-10-27 04:57 UTC, RimlTempest commented on composables/useReDraw.ts
> +                    if (target.active === true) {
trueの場合
```ts
if (target.active) {
~
}
```

で良い

2021-10-27 05:00 UTC, RimlTempest commented on composables/useReDraw.ts
> +) {
booleanで返すので返り値にbooleanを指定する

2021-10-27 05:09 UTC, RimlTempest commented on pages/creator/save.vue
> +                    ] = 999;
ここや他でも指定している999もenumか定数にしたものを利用する

2021-10-27 05:14 UTC, RimlTempest commented on store/modules/canvasData.ts
> +    // @Mutation
使わないなら消してよさそう

2021-10-27 05:15 UTC, RimlTempest commented on store/modules/canvasData.ts
> +            {
初期化用のオブジェクトを宣言して利用するようにする

2021-10-27 05:17 UTC, RimlTempest commented on pages/creator/canvas.vue
> +                <div class="layerListTest">
ここmolecuresとかにコンポーネント分けてpropsで値渡ししたほうが良さそう

2021-10-27 05:18 UTC, RimlTempest commented on pages/creator/canvas.vue
>              stackMaxSize: 100, // 巻き戻し可能な最大回数の設定
enumまたは定数にしたものを利用する

2021-10-27 05:19 UTC, RimlTempest commented on pages/creator/canvas.vue
>              canvasStyleSize: 334, // キャンバスの外見上のサイズ
enumまたは定数にしたものを利用する

2021-10-27 05:19 UTC, RimlTempest commented on pages/creator/canvas.vue
>              canvasSizeMagnification: 0.87, // キャンパスの表示倍率 外見上のサイズと整合性つけるため必要
enumまたは定数にしたものを利用する

2021-10-27 05:19 UTC, RimlTempest commented on pages/creator/canvas.vue
>              penMode: 'pen', // ペンのモード
enumまたは定数にしたものを利用する

2021-10-27 05:20 UTC, RimlTempest commented on pages/creator/canvas.vue
> +                    ] = 999; // 存在しうるレイヤーより大きく設定
enumまたは定数にしたものを利用する

2021-10-27 05:20 UTC, RimlTempest commented on pages/creator/canvas.vue
>                  case 'pen':
enumまたは定数にしたものを利用する

2021-10-27 05:26 UTC, RimlTempest commented on pages/creator/canvas.vue
> +                // TODO: アラートを出すかそもそも選択できなくするか
選択できなくしたほうが良さそう

2021-10-27 05:27 UTC, RimlTempest commented on pages/creator/canvas.vue
> +                // FIXME: もうちょっとコンパクトに出来そう・・・？
コンポーネント分けした際コンポーネント側で入れ替えの責務をもたせれば良さそう

2021-10-27 05:28 UTC, RimlTempest commented on pages/creator/canvas.vue
> +                // TODO: アラートを出すかそもそも選択できなくするか
選択できなくしたほうが良い

2021-10-27 05:29 UTC, RimlTempest commented on composables/useDrawDot.ts
> +    if (check === 1) {
enumまたは定数にしたものを利用する

2021-10-27 05:30 UTC, RimlTempest commented on composables/useDrawDot.ts
> +function checkCanvas(cell: Point, canvasData: CanvasType) {
返り値の型定義を行う

2021-10-27 05:31 UTC, RimlTempest commented on composables/useReDraw.ts
> +        canvasData.topLayerData[item] = 999; // キャンバスの一番上のレイヤーの情報を初期化
enumまたは定数にしたものを利用する

2021-10-27 05:32 UTC, RimlTempest requested changes
コメントしました

2021-10-29 05:46 UTC, RimlTempest commented on components/Molecules/LayerListTest.vue
> +<template>
ファイル名にTestと入っているのでTestを省く

2021-10-29 05:47 UTC, RimlTempest commented on composables/useLayerReDraw.ts
> +    if (canvasData.targetLayerData.active === false) {
falseなら`!canvasData.targetLayerData.active`でよさそう？

2021-10-29 05:49 UTC, RimlTempest commented on pages/creator/save.vue
> +                    ] = 999;
修正抜け？

2021-10-29 05:53 UTC, RimlTempest requested changes
修正漏れを修正してくれればOKそう

2021-10-29 06:13 UTC, RimlTempest reviewed
現状LGTM、レイヤー1つの場合も表示、非表示が可能に変更(今後画像を背景における場合を考慮)

2021-10-29 06:14 UTC, RimlTempest approved these changes
LGTM！

2021-10-29 06:15 UTC, merged